### ISSUE TITLE
수정요청

### ISSUE THREAD

**Issue by crongro** [cocoa-salon/cocoa-mine#1]
안녕하세요.

코드를 보고 수정요청드립니다.

1. var를 const와 let으로 변경
2. for 문을 제거하고, 대신 forEach라는 함수로 변경.

**Comment by cocoa-salon** [comment]
선생님 안녕하세요. 직접 피드백 남겨주셔서 감사합니다!  수정 사항의 forEach는 array.forEach() 함수인지 향상된 for 문인지 여쭤봐도 될지요.

**Comment by crongro** [comment]
forEach를사용해보세요.
그리고 가급적 어떻게 동작되는 것인지 설명도 주석으로 남겨주시면 좋겠어요.

**Comment by cocoa-salon** [comment]
선생님, 요청주신 내용에 따라 수정하여 커밋, 푸시하였사오니 확인 부탁드립니다. 감사합니다.

**Comment by crongro** [comment]
잘 하셨어요.
확인 했습니다. :-)
@cocoa-salon
